= Hola Hubpress

= Soy un H1

== Soy un H2 

:uri-rackcode: http://rackcode.info

La plataforma de {uri-rackcode}[Rackcpde]

== http://rackcode.info[Rackcode] 



Hubpress - Curso Profesional de Github con Hubpress

HubPress es una aplicaci칩n web para construir un blog en GitHub escrito en Javascript.

Hubpress nos permite crear un blog unicamente haciendo un fork del proyecto en Github. Este proyecto esta dando sus primeros pasos a ser una posible competencia en un futuro a Wordpress, Blogger o Ghost, La diferencia ante los ya mencionados es que Hubpress es sencillamente facil y rapido de instalar. 

Hubpress es gratuito , todo lo que necesitas es una cuenta gratuita GitHub , no requiere ningun servidor, ni suscripci칩n ,
    
Tiene una f치cil configuraci칩n, puedes integrar Disqus ademas de Google Analitics.

Este sin duda es un proyecto que nos a llamado mucho la atencion y que no vamos a perder de vista. Si quieres saber mas de Hubpress entra ya al curso de Profesional de Github con Hubpress.


